# Import Libraries :

In [120]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importing the Dataset : (wine Quality)

In [121]:
wine = pd.read_csv("winequality_red.csv")

In [122]:
wine

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [10]:
pd.set_option('display.max_rows',100)

In [11]:
wine

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [12]:
wine['quality'].unique()

array([5, 6, 7, 4, 8, 3], dtype=int64)

# No null values found in the Dataset :

In [13]:
wine.isna().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [14]:
x_ind = wine.drop(['quality'],axis=1)

In [15]:
x_ind

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  
0         9.4  
1         9.8  
2         9.8  
3         9.8  
4         9.4  
...       ...  
1594     10.5  
1595     11.2  
1596     11.0  
1597     10.2  
1598     11.0  

[1599 rows x 11 columns]

In [16]:
y_dep= wine.quality

In [18]:
y_dep

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

# Train_test_split : 

In [123]:
from sklearn.model_selection import train_test_split

In [124]:

x_train,x_test,y_train,y_test = train_test_split(x_ind,y_dep,test_size=0.2,random_state=3)

# Random Forest :

In [125]:
from sklearn.ensemble import RandomForestClassifier

In [126]:
RF = RandomForestClassifier(random_state=1)

In [127]:
RF_fit= RF.fit(x_train,y_train)

# prediction :

In [128]:
y_pred = RF_fit.predict(x_test)

In [129]:
y_pred

array([5, 6, 6, 6, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 7, 5, 6, 5, 7, 6, 7, 5,
       6, 5, 6, 5, 5, 6, 5, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5, 6, 6, 5, 7, 6,
       5, 5, 6, 5, 5, 6, 5, 5, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6,
       5, 6, 5, 6, 5, 5, 6, 5, 6, 6, 6, 5, 6, 6, 6, 6, 5, 6, 5, 5, 5, 5,
       6, 5, 6, 6, 6, 5, 5, 6, 5, 5, 6, 7, 6, 5, 6, 7, 6, 5, 5, 5, 5, 6,
       7, 5, 7, 6, 5, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 6,
       5, 5, 7, 5, 6, 6, 5, 6, 5, 7, 5, 5, 6, 5, 6, 6, 6, 5, 5, 6, 6, 5,
       5, 6, 6, 5, 5, 6, 5, 6, 6, 6, 5, 6, 5, 6, 5, 5, 6, 7, 5, 6, 6, 5,
       5, 5, 6, 6, 7, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 7, 5, 5, 6, 5, 6, 6,
       6, 5, 5, 5, 7, 6, 6, 5, 5, 7, 5, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 5,
       5, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5, 5, 7, 5, 5, 6, 6,
       6, 5, 8, 7, 6, 5, 5, 6, 5, 5, 6, 6, 5, 6, 7, 5, 6, 5, 7, 7, 6, 5,
       5, 8, 5, 6, 5, 5, 6, 6, 6, 6, 7, 6, 5, 5, 5, 5, 6, 5, 5, 6, 5, 6,
       5, 5, 6, 6, 5, 7, 5, 5, 6, 6, 5, 6, 6, 7, 6,

# confusion Matrix :

In [130]:
from sklearn.metrics import confusion_matrix ,accuracy_score

In [131]:
CM_RF = confusion_matrix(y_test,y_pred)
CM_RF

array([[  0,   0,   2,   0,   0,   0],
       [  0,   0,   9,   3,   0,   0],
       [  0,   0, 117,  21,   0,   0],
       [  0,   0,  26,  99,   6,   0],
       [  0,   0,   1,  15,  18,   2],
       [  0,   0,   0,   1,   0,   0]], dtype=int64)

In [132]:
accuracy = accuracy_score(y_test,y_pred)

In [133]:
accuracy

0.73125

# Hyper Parametric :

In [134]:
from sklearn.model_selection import RandomizedSearchCV

In [135]:
parameters = {'n_estimators':(200,300,400,500,600),'criterion':('gini','entropy'),'max_features':('auto','sqrt'),"min_samples_split":(2,4,6)}

In [136]:
parameters

{'n_estimators': (200, 300, 400, 500, 600),
 'criterion': ('gini', 'entropy'),
 'max_features': ('auto', 'sqrt'),
 'min_samples_split': (2, 4, 6)}

In [101]:
RF_grid=RandomizedSearchCV(RandomForestClassifier(),param_distributions=parameters,cv=5)

In [102]:
RF_grid.fit(x_train,y_train)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ('gini', 'entropy'),
                                        'max_features': ('auto', 'sqrt'),
                                        'min_samples_split': (2, 4, 6),
                                        'n_estimators': (200, 300, 400, 500,
                                                         600)})

In [103]:
RF_grid.best_estimator_

RandomForestClassifier(criterion='entropy', min_samples_split=6,
                       n_estimators=600)

# After Hyper Parametric test :

In [161]:
RF_HP = RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=6,
                       min_weight_fraction_leaf=0.0, n_estimators=600,
                       n_jobs=None, oob_score=False, random_state=3,
                       verbose=0, warm_start=False)

In [162]:
RF_HP_fit=RF_HP.fit(x_train,y_train)

# After predict 

In [163]:
y_pred_HP = RF_HP_fit.predict(x_test)

In [164]:
y_pred_HP

array([5, 6, 6, 6, 5, 5, 5, 6, 5, 5, 6, 5, 5, 5, 7, 5, 6, 5, 7, 6, 7, 5,
       6, 5, 5, 5, 5, 6, 5, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5, 6, 6, 5, 7, 6,
       5, 5, 6, 5, 5, 6, 5, 6, 6, 6, 6, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6,
       5, 6, 5, 6, 6, 5, 6, 5, 6, 6, 6, 5, 6, 6, 6, 6, 5, 6, 5, 5, 5, 5,
       6, 5, 6, 6, 6, 5, 5, 6, 5, 5, 6, 7, 6, 5, 6, 6, 6, 5, 5, 5, 5, 6,
       6, 5, 7, 6, 5, 5, 5, 5, 6, 6, 6, 5, 6, 5, 6, 6, 6, 6, 6, 5, 5, 6,
       6, 5, 7, 5, 6, 6, 5, 6, 5, 7, 5, 5, 6, 5, 6, 6, 7, 5, 5, 6, 6, 5,
       5, 6, 6, 5, 5, 6, 6, 6, 5, 6, 5, 6, 5, 6, 5, 5, 6, 7, 5, 6, 6, 5,
       5, 5, 6, 6, 7, 6, 6, 6, 5, 6, 5, 6, 7, 6, 6, 7, 5, 5, 6, 5, 6, 6,
       6, 5, 5, 5, 7, 6, 6, 5, 5, 7, 5, 5, 6, 5, 5, 5, 6, 6, 6, 5, 5, 5,
       5, 5, 6, 5, 6, 5, 6, 5, 6, 5, 6, 5, 5, 6, 5, 5, 5, 7, 5, 5, 6, 6,
       6, 5, 8, 7, 6, 5, 5, 6, 5, 5, 6, 6, 5, 6, 7, 5, 6, 5, 6, 7, 6, 6,
       5, 7, 5, 6, 5, 5, 6, 6, 6, 6, 7, 6, 5, 5, 5, 5, 6, 5, 5, 6, 5, 6,
       5, 5, 6, 6, 5, 7, 5, 5, 6, 6, 5, 6, 6, 7, 6,

# Confusion Matrix :

In [165]:
CM_HP = confusion_matrix(y_test,y_pred_HP)

In [166]:
CM_HP

array([[  0,   0,   2,   0,   0,   0],
       [  0,   0,   8,   4,   0,   0],
       [  0,   0, 117,  21,   0,   0],
       [  0,   0,  26, 101,   4,   0],
       [  0,   0,   1,  14,  20,   1],
       [  0,   0,   0,   1,   0,   0]], dtype=int64)

In [167]:
Acc_HP = accuracy_score(y_test,y_pred_HP)

In [168]:
Acc_HP

0.74375